#!/bin/sh
#
# Gradle start up script for UNIX (generated by Android Studio)
#

# Attempt to set APP_HOME
# Resolve links: starting with "$0", then prepend the directory where the file resides
APP_HOME=$(cd "$(dirname "$0")" && pwd)
echo "Gradle home: $APP_HOME"

# Find the java executable
if [ -z "$JAVA_HOME" ]; then
    JAVACMD="java"
else
    JAVACMD="$JAVA_HOME/bin/java"
fi

# Check if java is available
if ! command -v "$JAVACMD" 2>/dev/null >/dev/null 2>&1; then
    echo "ERROR: java is required but not found."
    exit 1
fi

# Set default ANDROID_HOME
if [ -z "$ANDROID_HOME" ]; then
    export ANDROID_HOME="$HOME/Android/Sdk"
fi
export ANDROID_SDK_ROOT="$ANDROID_HOME"

# Add SDK tools to PATH
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

# Add gradle bin to classpath
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
